$font = IosevkaTerm NFP

$background = rgb(33, 33, 33)
$background2 = rgb(41, 41, 41)
$text = rgb(170, 190, 197)
$accent = rgb(130, 170, 255)
$red = rgb(255, 83, 112)
# GENERAL
general {
  hide_cursor = true
}

# BACKGROUND
background {
  monitor =
  path = screenshot
  blur_passes = 3
  color = $background
}

# TIME
label {
  monitor =
  text = $TIME
  color = $text
  font_size = 90
  font_family = $font
  position = 0, 0
  halign = center
  valign = top
}

# DATE
label {
  monitor =
  text = cmd[update:43200000] date +"%A, %d %B %Y"
  color = $text
  font_size = 25
  font_family = $font
  position = 0, -150
  halign = center
  valign = top
}



# USER AVATAR
image {
  monitor =
  path = $HOME/.face
  size = 100
  border_color = $accent
  position = 0, 75
  halign = center
  valign = center
}

# INPUT FIELD
input-field {
  monitor =
  size = 300, 60
  outline_thickness = 2
  dots_size = 0.3
  dots_spacing = 0.2
  dots_center = true
  outer_color = $accent
  inner_color = $background2
  font_color = $text
  rounding = 0
  fade_on_empty = false
  placeholder_text = <span font_size="18pt">  </span>
  hide_input = false
  check_color = $accent
  fail_color = $red
  fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
  position = 0, -47
  halign = center
  valign = center
}
